# Generated by Django 5.2.16 on 2026-07-28 08:45
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, db_index=True, max_length=32)),
                ('is_customer', models.BooleanField(default=False)),
                ('is_supplier', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CounterpartyAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('name', '名称'), ('bank_account', '银行账号'), ('wechat_name', '微信名称'), ('collection_account', '代收账户')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('normalized_value', models.CharField(max_length=255)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='parties.counterparty')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'normalized_value'), name='uniq_party_alias_kind_value')],
            },
        ),
    ]
