# Generated by Django 5.2.16 on 2026-07-28 08:45
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('bank', '银行'), ('wechat', '微信')], max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('identifier', models.CharField(max_length=100)),
                ('masked_identifier', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountBalanceSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of', models.DateTimeField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.importbatch')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_snapshots', to='ledger.fundingaccount')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('account', 'as_of'), name='uniq_account_balance_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('input', '进项'), ('output', '销项')], max_length=10)),
                ('invoice_number', models.CharField(max_length=30)),
                ('seller_tax_id', models.CharField(max_length=32)),
                ('buyer_tax_id', models.CharField(max_length=32)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('normal', '正常'), ('void', '作废'), ('red', '红冲')], max_length=12)),
                ('source_row', models.PositiveIntegerField()),
                ('source_payload', models.JSONField(default=dict)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parties.counterparty')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.importbatch')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='invoice_total_amount_positive'), models.UniqueConstraint(fields=('invoice_number', 'seller_tax_id'), name='uniq_invoice_number_seller_tax_id')],
            },
        ),
        migrations.CreateModel(
            name='MoneyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('bank', '银行'), ('wechat', '微信')], max_length=12)),
                ('direction', models.CharField(choices=[('inflow', '收入'), ('outflow', '支出')], max_length=10)),
                ('occurred_at', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('counterparty_raw_name', models.CharField(blank=True, max_length=255)),
                ('counterparty_account', models.CharField(blank=True, max_length=100)),
                ('source_row', models.PositiveIntegerField()),
                ('source_payload', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.fundingaccount')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='parties.counterparty')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imports.importbatch')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='money_transaction_amount_positive'), models.CheckConstraint(condition=models.Q(('channel__in', ['bank', 'wechat'])), name='money_transaction_channel_valid'), models.CheckConstraint(condition=models.Q(('direction__in', ['inflow', 'outflow'])), name='money_transaction_direction_valid')],
            },
        ),
    ]
