# Generated by Django 5.2.16 on 2026-07-28 12:06
# ruff: noqa: RUF012

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ledger', '0002_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['linked', 'unclaimed'])), name='attachment_status_valid'),
        ),
    ]
