# Generated by Django 5.2.16 on 2026-07-28 09:26
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('purchase_payment', '采购付款'), ('sales_receipt', '销售收款')], max_length=20)),
                ('mode', models.CharField(choices=[('direct', '直接核销')], default='direct', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='ReconciliationAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.invoice')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='reconciliation.reconciliation')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.moneytransaction')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='reconciliation_allocation_amount_positive')],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationReversal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='reconciliation.reconciliation')),
                ('reversed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
