# Generated by Django 5.2.16 on 2026-07-28
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0001_initial"),
        ("parties", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reconciliation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementBatch",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("direction", models.CharField(choices=[("purchase_payment", "采购付款"), ("sales_receipt", "销售收款")], max_length=20)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status", models.CharField(choices=[("draft", "草稿"), ("confirmed", "已确认")], default="draft", max_length=12)),
                ("version", models.PositiveIntegerField(default=1)),
                ("counterparty", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="parties.counterparty")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SettlementBatchInvoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoice_items", to="reconciliation.settlementbatch")),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ledger.invoice")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "invoice"),
                        name="uniq_settlement_batch_invoice",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SettlementBatchTransaction",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("batch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transaction_items", to="reconciliation.settlementbatch")),
                ("transaction", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ledger.moneytransaction")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "transaction"),
                        name="uniq_settlement_batch_transaction",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="reconciliation",
            name="settlement_batch",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reconciliations", to="reconciliation.settlementbatch"),
        ),
        migrations.AlterField(
            model_name="reconciliation",
            name="mode",
            field=models.CharField(
                choices=[("direct", "直接核销"), ("batch", "批次核销")],
                default="direct",
                max_length=10,
            ),
        ),
    ]
