# Generated by Django 5.2.16 on 2026-08-07
# ruff: noqa: RUF012

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.system_update.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemUpdateRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.UUIDField(unique=True)),
                (
                    "target_version",
                    models.CharField(
                        max_length=32,
                        validators=[apps.system_update.models.validate_release_version],
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("active", "进行中"),
                            ("succeeded", "成功"),
                            ("failed", "失败"),
                            ("manual_intervention", "需要人工处理"),
                        ],
                        max_length=24,
                    ),
                ),
                ("terminal_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("result__in", [
                                "active",
                                "succeeded",
                                "failed",
                                "manual_intervention",
                            ])
                        ),
                        name="system_update_request_result_valid",
                    ),
                ],
            },
        ),
    ]
