# Generated by Django 5.2.16 on 2026-07-28 08:18
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.imports.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('input_invoice', '进项发票'), ('output_invoice', '销项发票'), ('bank', '银行'), ('wechat', '微信')], max_length=20)),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('previewed', '已预检'), ('partial', '部分完成'), ('completed', '已完成')], default='uploaded', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.imports.storage.source_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('size', models.PositiveBigIntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_files', to='imports.importbatch')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='StagedRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('normalized_data', models.JSONField(default=dict)),
                ('issues', models.JSONField(default=list)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
            ],
            options={
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status'], name='imports_imp_status_22f3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['source_kind'], name='imports_imp_source__1439f8_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['period_start'], name='imports_imp_period__d6211a_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['period_end'], name='imports_imp_period__5e3290_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedrow',
            index=models.Index(fields=['batch', 'posted_at'], name='imports_sta_batch_i_33696f_idx'),
        ),
        migrations.AddIndex(
            model_name='stagedrow',
            index=models.Index(fields=['is_duplicate'], name='imports_sta_is_dupl_56d80a_idx'),
        ),
        migrations.AddConstraint(
            model_name='stagedrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='uniq_staged_row_number'),
        ),
    ]
