# Generated by Django 5.2.16 on 2026-07-28 11:54
# ruff: noqa: RUF012

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCoveragePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('source_kind', models.CharField(choices=[('input_invoice', '进项发票'), ('output_invoice', '销项发票'), ('bank', '银行'), ('wechat', '微信')], max_length=20)),
                ('status', models.CharField(choices=[('full', '完整'), ('partial', '部分缺失'), ('missing', '缺失')], max_length=12)),
                ('expected_start', models.DateField()),
                ('expected_end', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('missing_notes', models.TextField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'source_kind'), name='uniq_data_coverage_period'), models.CheckConstraint(condition=models.Q(('expected_start__lte', models.F('expected_end'))), name='data_coverage_expected_dates_ordered'), models.CheckConstraint(condition=models.Q(models.Q(('actual_end__isnull', True), ('actual_start__isnull', True)), models.Q(('actual_end__isnull', False), ('actual_start__isnull', False), ('actual_start__lte', models.F('actual_end'))), _connector='OR'), name='data_coverage_actual_dates_ordered')],
            },
        ),
    ]
