# Generated by Django 5.2.16 on 2026-07-28 12:06
# ruff: noqa: RUF012

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_data_coverage'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datacoverageperiod',
            name='data_coverage_actual_dates_ordered',
        ),
        migrations.AddConstraint(
            model_name='datacoverageperiod',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['full', 'partial', 'missing'])), name='data_coverage_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='datacoverageperiod',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actual_end__isnull', True), ('actual_start__isnull', True), ('status', 'missing')), models.Q(('actual_end__isnull', False), ('actual_end__lte', models.F('expected_end')), ('actual_start__gte', models.F('expected_start')), ('actual_start__isnull', False), ('actual_start__lte', models.F('actual_end')), ('status__in', ['full', 'partial'])), _connector='OR'), name='data_coverage_actual_range_valid'),
        ),
    ]
